- name: add ubuntu keyserver
  shell: apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF

- name: mesosphere repo setup
  lineinfile: > 
    dest=/etc/apt/sources.list.d/mesosphere.list
    create=yes
    line="deb http://{{ repo }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"

- name: update /etc/hosts
  lineinfile: >
    insertbefore=BOF
    dest=/etc/hosts
    line="{{ ansible_eth1.ipv4.address }} {{ ohai_hostname }}"

- debug: msg="{{ item.0 }} and {{ item.1 }}"
  with_together:
    - slave_ips
    - slave_hostnames


- name: append slaves to /etc/hosts
  lineinfile: >
    insertbefore=BOF
    dest=/etc/hosts
    line="{{ item.0 }} {{ item.1 }}"
  with_together:
    - slave_ips
    - slave_hostnames

- name: install software
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - python-setuptools
    - python-pip
    - mesos
    - marathon
    - chronos

- name: install python bindings
  easy_install: name={{ python_bindings }}

- name: install mesos cli
  pip: name=mesos.cli

- name: mesosphere ip configuration
  lineinfile: > 
    dest={{ item }}
    create=yes
    line={{ ansible_eth1.ipv4.address }}
  with_items:
    - /etc/mesos-master/ip

- name: start mesos services
  service: name={{ item }} state=started
  with_items:
    - mesos-master
    - marathon
    - chronos
