- name: Deploy Mesos master node
  hosts: all
  sudo: True

  vars: 
    python_bindings: http://downloads.mesosphere.io/master/ubuntu/14.04/mesos-0.22.1-py2.7-linux-x86_64.egg
    repo: repos.mesosphere.io
  tasks:
    - name: add ubuntu keyserver
      shell: apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF

    - name: mesosphere repo setup
      lineinfile: > 
        dest=/etc/apt/sources.list.d/mesosphere.list
        create=yes
        line="deb http://{{ repo }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"

    - name: update /etc/hosts
      lineinfile: >
        dest=/etc/hosts
        line="{{ ansible_eth1.ipv4.address }} {{ ohai_hostname }}"

    - name: install software
      apt: pkg={{ item }} update_cache=yes
      with_items:
        - python-setuptools
        - mesos
        - marathon
        - chronos

    - name: install python bindings
      easy_install: name={{ python_bindings }}

    - name: mesosphere ip configuration
      lineinfile: > 
        dest={{ item }}
        create=yes
        line={{ ansible_eth1.ipv4.address }}
      with_items:
        - /etc/mesos-master/ip

    - name: start mesos services
      service: name={{ item }} state=started
      with_items:
        - mesos-master
        - marathon
