- name: download and install docker
  shell: "wget -qO- {{ docker_url }} | sh"

- name: configure priority of docker containerizer
  lineinfile: >
    dest=/etc/mesos-slave/containerizers
    create=yes
    line="docker,mesos"
  notify:
    - restart mesos-slave

- name: increase the executor timeout for pulling docker images
  lineinfile: >
    dest=/etc/mesos-slave/executor_registration_timeout
    create=yes
    line="5mins"
  notify:
    - restart mesos-slave
