- name: add ubuntu keyserver
  shell: apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF

- name: mesosphere repo setup
  lineinfile: > 
    dest=/etc/apt/sources.list.d/mesosphere.list
    create=yes
    line="deb http://{{ repo }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"

- name: update /etc/hosts
  lineinfile: >
    insertbefore=BOF
    dest=/etc/hosts
    line="{{ item }}"
  with_items:
    - "{{ ansible_eth1.ipv4.address }} {{ ohai_hostname }}"
    - "{{ master_ip }} {{ master_hostname }}"

- name: install software
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - mesos

- name: mesosphere ip configuration
  lineinfile: > 
    dest={{ item }}
    create=yes
    line={{ ansible_eth1.ipv4.address }}
  with_items:
    - /etc/mesos-slave/ip

- name: configure Zookeeper
  template: "src=templates/zk.j2 dest=/etc/mesos/zk"

- name: start mesos services
  service: name={{ item }} state=started
  with_items:
    - mesos-slave
