- name: install nginx
  shell: apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF

- name: mesosphere repo setup
  lineinfile: > 
    dest=/etc/apt/sources.list.d/mesosphere.list
    create=yes
    line="deb http://{{ repo }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"

- name: update /etc/hosts
  lineinfile: >
    dest=/etc/hosts
    line="{{ ansible_eth1.ipv4.address }} {{ ohai_hostname }}"

- name: install software
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - python-setuptools
    - mesos
    - marathon
    - chronos

- name: install python bindings
  easy_install: name={{ python_bindings }}

- name: mesosphere ip configuration
  lineinfile: > 
    dest={{ item }}
    create=yes
    line={{ ansible_eth1.ipv4.address }}
  with_items:
    - /etc/mesos-master/ip
    - /etc/mesos-slave/ip

- name: start mesos services
  service: name={{ item }} state=started
  with_items:
    - mesos-master
    - mesos-slave
    - marathon
    - chronos
